services:
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev
    ports:
      - "5001:80"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=osprey-postgres-database-1 # NOTE: Make sure it is the same as the database-name
      - DATABASE_NAME=osprey_development
      - FLASK_APP=server.py

      # Project owner registers this
      - GLOBUS_FLOW_DOWNLOAD_FUNCTION=2f7a2bd6-39ee-4866-b64e-abc290110d98
      - GLOBUS_FLOW_COMMIT_FUNCTION=5a5cd5e5-bfd5-4a86-8344-d31d226ab8a4
      - GLOBUS_FLOW_USER_COMMIT_FUNCTION=957ca7fc-aafe-4c10-b40a-469e6ff494aa

      # User functions are registered in this client
      # - FUNCX_SDK_CLIENT_ID=638156ef-7332-4ab1-8d92-304b27bdd270
      # - FUNCX_SDK_CLIENT_SECRET=zUtPdMO1HDdRI3Qjkjehgn6YA85griFVJlwgu/HLbl4=

      - GLOBUS_WORKER_UUID=341dda3d-5b98-46a8-9d47-2070bc12b1db
      - GCS_ENDPOINT_UUID=ede1f1ef-8c15-42fd-a3ce-3ca6109bce42
      - GCS_MANAGER_DOMAIN_NAME=6073d3.08cc.data.globus.org
      - GCS_STORAGE_GATEWAY_ID=88cba8d2-5a8b-439c-8a53-74a2f0332128
      - GCS_MAPPED_COLLECTION_ID=f36c1eb6-7d6a-4bf0-973f-e4adf052b34e
      - GCS_SERVICE_USER=sudershan
      - CONNECTOR_ID=88cba8d2-5a8b-439c-8a53-74a2f0332128
    volumes:
      - ./osprey:/app/osprey
      - ./data:/app/osprey/data
    depends_on:
        - postgres-database
        - globus-endpoint

  postgres-database:
    restart: always
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - osprey-postgres-data:/var/lib/postgresql/data

  globus-endpoint:
    build:
        dockerfile: ./Dockerfiles/Dockerfile.endpoint.dev
    volumes:
      - osprey-endpoint-data:/root/.globus_compute
      - ./osprey:/app/osprey
      - ./data:/app/osprey/data

    # TODO: Make a different user
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=osprey-postgres-database-1
      - DATABASE_NAME=osprey_development
      # - FUNCX_SDK_CLIENT_ID=638156ef-7332-4ab1-8d92-304b27bdd270
      # - FUNCX_SDK_CLIENT_SECRET=zUtPdMO1HDdRI3Qjkjehgn6YA85griFVJlwgu/HLbl4=

  # globus-connect:
  #     build:
  #       dockerfile: ./Dockerfiles/Dockerfile.connect-server.dev
  #     volumes:
  #       - ./osprey/:/app/osprey/
  #     ports:
  #       - "443:443"
  #       - "80:80"
  #     tty: true
  #     stdin_open: true

  # globus-proxystore:
  #   build:
  #     dockerfile: ./Dockerfiles/Dockerfile.proxystore.dev
  #   volumes:
  #     - osprey-proxystore-data:/root/.local/share/proxystore
  #   ports:
  #     - "8765:8765"

volumes:
  osprey-postgres-data:
    external: true
  osprey-endpoint-data:
    external: true
  osprey-proxystore-data:
    external: true