services:
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev
    ports:
      - "5001:80"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=dsaas-postgres-database-1 # NOTE: Make sure it is the same as the database-name
      - DATABASE_NAME=osprey_development
      - PORTAL_CLIENT_ID=${PORTAL_CLIENT_ID}
      - PORTAL_CLIENT_SECRET=${PORTAL_CLIENT_SECRET}
      - FLASK_APP=app/run.py

      # Project owner registers this
      - GLOBUS_FLOW_DOWNLOAD_FUNCTION=330e9240-70a0-47be-98a5-3354c7fcba5a
      - GLOBUS_FLOW_COMMIT_FUNCTION=0037e1ac-749b-4006-be57-75d933b02665
      - GLOBUS_FLOW_USER_COMMIT_FUNCTION=45276e86-7ac3-4e8e-8d06-10870c173d77
      - SEARCH_INDEX=8bbcdadc-46ae-4a45-8cd6-e80ea85d7afd
      # For timer email
      - DSAAS_EMAIL_PASSWORD=${DSAAS_EMAIL_PASSWORD}

    volumes:
      - ./osprey:/app/osprey
      - ./data:/app/osprey/data
    depends_on:
        - postgres-database

  postgres-database:
    restart: always
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=osprey_development
    ports:
      - "5432:5432"
    volumes:
      - osprey-postgres-data:/var/lib/postgresql/data
volumes:
  osprey-postgres-data:
    external: true
