services:
  smtp-server:
    env_file: ./smtp/.env
    build:
      dockerfile: ./Dockerfiles/Dockerfile.smtp.dev
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    ports:
      - ${PORT}:25
  web:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.server.dev
    ports:
      - "5001:80"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=osprey-postgres-database-1 # NOTE: Make sure it is the same as the database-name
      - DATABASE_NAME=osprey_development
      - FLASK_APP=server.py

      # Project owner registers this
      - GLOBUS_FLOW_DOWNLOAD_FUNCTION=acafb28d-7925-4b0f-92f0-301193c1a204
      - GLOBUS_FLOW_COMMIT_FUNCTION=52d4fca5-e1b8-4ba2-bec3-4149c9bbb8ce
      - GLOBUS_FLOW_USER_COMMIT_FUNCTION=3307825c-00c0-4e46-ae01-00482fb8e351

      # User functions are registered in this client
      # - FUNCX_SDK_CLIENT_ID=638156ef-7332-4ab1-8d92-304b27bdd270
      # - FUNCX_SDK_CLIENT_SECRET=zUtPdMO1HDdRI3Qjkjehgn6YA85griFVJlwgu/HLbl4=

      - GLOBUS_WORKER_UUID=28054165-5187-4d29-9ba8-451478e4eb7c
      - GCS_ENDPOINT_UUID=ede1f1ef-8c15-42fd-a3ce-3ca6109bce42
      - GCS_MANAGER_DOMAIN_NAME=6073d3.08cc.data.globus.org
      - GCS_STORAGE_GATEWAY_ID=88cba8d2-5a8b-439c-8a53-74a2f0332128
      - GCS_MAPPED_COLLECTION_ID=f36c1eb6-7d6a-4bf0-973f-e4adf052b34e
      - GCS_SERVICE_USER=sudershan
      - CONNECTOR_ID=88cba8d2-5a8b-439c-8a53-74a2f0332128
    volumes:
      - ./osprey:/app/osprey
      - ./data:/app/osprey/data
      - ./globus_compute/:/root/.globus_compute/
    depends_on:
        - postgres-database
        - globus-endpoint

  postgres-database:
    restart: always
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - osprey-postgres-data:/var/lib/postgresql/data

  globus-endpoint:
    build:
        dockerfile: ./Dockerfiles/Dockerfile.endpoint.dev
    volumes:
      - osprey-endpoint-data:/root/.globus_compute
      - ./osprey:/app/osprey
      - ./data:/app/osprey/data

    # TODO: Make a different user
    environment:
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=osprey-postgres-database-1
      - DATABASE_NAME=osprey_development
      # - FUNCX_SDK_CLIENT_ID=638156ef-7332-4ab1-8d92-304b27bdd270
      # - FUNCX_SDK_CLIENT_SECRET=zUtPdMO1HDdRI3Qjkjehgn6YA85griFVJlwgu/HLbl4=

  # globus-connect:
  #     build:
  #       dockerfile: ./Dockerfiles/Dockerfile.connect-server.dev
  #     volumes:
  #       - ./osprey/:/app/osprey/
  #     ports:
  #       - "443:443"
  #       - "80:80"
  #     tty: true
  #     stdin_open: true

  # globus-proxystore:
  #   build:
  #     dockerfile: ./Dockerfiles/Dockerfile.proxystore.dev
  #   volumes:
  #     - osprey-proxystore-data:/root/.local/share/proxystore
  #   ports:
  #     - "8765:8765"

volumes:
  osprey-postgres-data:
    external: true
  osprey-endpoint-data:
    external: true
  osprey-proxystore-data:
    external: true